CREATE TABLE user_info (
    user_id VARCHAR(255) NOT NULL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE role (
    role_id BIGINT NOT NULL,
    role VARCHAR(255),
    PRIMARY KEY (role_id)
);

CREATE TABLE token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY ,
    token VARCHAR(255) NOT NULL,
    expiry_date TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES user_info(user_id)
);

CREATE TABLE user_role (
    user_id VARCHAR(255) NOT NULL ,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT FK_user_info FOREIGN KEY (user_id) REFERENCES user_info(user_id),
    CONSTRAINT FK_role FOREIGN KEY (role_id) REFERENCES role(role_id)
);

CREATE SEQUENCE role_seq START WITH 1 INCREMENT BY 1;
ALTER SEQUENCE role_seq OWNER TO rajsubhod;
ALTER SEQUENCE role_seq OWNED BY role.role_id;

-- CREATE SEQUENCE token_id_seq START WITH 1 INCREMENT BY 20;
-- ALTER SEQUENCE token_id_seq OWNER TO rajsubhod;
-- ALTER SEQUENCE token_id_seq OWNED BY token.id;



INSERT INTO role (role_id, role) VALUES (nextval('role_seq'), 'ROLE_ADMIN');
INSERT INTO role (role_id, role) VALUES (nextval('role_seq'), 'ROLE_USER');
